apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  DATABASE_URL: "jdbc:postgresql://your-rds-endpoint.amazonaws.com:5432/payment_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-payment-secrets
data:
  POSTGRES_DB: cGF5bWVudF9kYg==
  POSTGRES_PASSWORD: cGF5bWVudF91c2Vy
  POSTGRES_USER: cGF5bWVudF91c2Vy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: aggkov/payment-service:1.0.1
          ports:
            - containerPort: 8445
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-payment-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-payment-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8445
      targetPort: 8445
  type: ClusterIP